keys:
  - &workstation age1pmnz0hgg05ej9e8jdgpwuhpd0llpe7aegkur3v0qcawt7yx5nqjqgyldrt
  - &nucbox age1qu7q27f5u9zewwvs4hd8s0ulztkh9c4stgeywrg25dfs5qugve8qulcvp6

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *workstation
          - *nucbox
