version: '3'

tasks:
  rebuild-nucbox:
    vars:
      NUCBOX_USER: nikita
      NUCBOX_HOST: 192.168.1.127
    cmds:
      - |
        nix run nixpkgs#nixos-rebuild -- \
            switch \
            --flake .#nucbox \
            --target-host {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} \
            --build-host {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} \
            --sudo
