version: '3'

vars:
  NUCBOX_USER: nikita
  NUCBOX_HOST: 192.168.1.136
  NUCBOX_NOMAD_JOBS_DIR: /home/{{ .NUCBOX_USER }}/nomad-jobs

tasks:
  auth:generate-user:
    cmds:
      - docker run --rm -it authelia/authelia:latest authelia crypto hash generate argon2

  auth:oidc:generate-jwks-key:
    cmds:
      - openssl genrsa 4096

  auth:oidc:generate-client-secret:
    cmds:
      - docker run --rm authelia/authelia:latest authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986

  auth:oidc:issue-token:
    deps: [sops:decrypt]
    cmds:
      - |
        export _oidc_secret=$(uv run scripts/get-content.py nomad/jobs/authelia/secrets/testing_oidc_client_secret.raw.yaml)
        export _oidc_state=$(cat /dev/urandom | head -c 30 | base64)

        oidc-cli \
          authorization_code \
            -authorization-url https://auth.cdayz.ru/api/oidc/authorization \
            -pkce \
            -auth-method client_secret_basic \
            -client-id oidc-cli \
            -client-secret $_oidc_secret \
            -issuer https://auth.cdayz.ru \
            -state $_oidc_state

  auth:random-string:
    cmds:
      - cat /dev/urandom | head -c 30 | base64

  auth:httpaswd:
    cmds:
      - docker run --rm httpd:2.4-alpine htpasswd -nbB agent {{ .CLI_ARGS }}

  sops:encrypt:
    desc: Encrypt raw secret files
    cmds:
      - PYTHONPATH=. uv run scripts/encrypt-secrets.py

  sops:decrypt:
    desc: Decrypt tracked secret files into local raw copies
    cmds:
      - PYTHONPATH=. uv run scripts/decrypt-secrets.py

  nucbox:rebuild:
    dir: nixos
    deps: [sops:encrypt]
    cmds:
      - |
        nix run nixpkgs#nixos-rebuild -- \
            switch \
            --flake .#nucbox \
            --target-host {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} \
            --build-host {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} \
            --sudo

  nucbox:rebuild:test:
    dir: nixos
    deps: [sops:encrypt]
    cmds:
      - |
        nix run nixpkgs#nixos-rebuild -- \
            test \
            --flake .#nucbox \
            --target-host {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} \
            --build-host {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} \
            --sudo

  nomad:render:
    desc: Render nomad job directory
    deps: [sops:encrypt]
    cmds:
      - PYTHONPATH=. uv run scripts/render-nomad-job.py --job-name {{ .CLI_ARGS }} --remote-jobs-dir {{ .NUCBOX_NOMAD_JOBS_DIR }}

  nucbox:nomad:plan:
    desc: Render and plan nomad job
    deps: [sops:encrypt]
    cmds:
      - task: nomad:render
        vars:
          CLI_ARGS: "{{ .CLI_ARGS }}"
      - ssh {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} "sudo rm -rf {{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }} && mkdir -p {{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }}"
      - rsync -a nomad/render/{{ .CLI_ARGS }}/ {{.NUCBOX_USER}}@{{.NUCBOX_HOST}}:{{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }}/
      - ssh {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} "nomad job plan {{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }}/job.hcl"

  nucbox:nomad:deploy:
    desc: Render and deploy nomad job
    deps: [sops:encrypt]
    cmds:
      - task: nomad:render
        vars:
          CLI_ARGS: "{{ .CLI_ARGS }}"
      - ssh {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} "sudo rm -rf {{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }} && mkdir -p {{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }}"
      - rsync -a nomad/render/{{ .CLI_ARGS }}/ {{.NUCBOX_USER}}@{{.NUCBOX_HOST}}:{{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }}/
      - ssh {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} "nomad job run {{.NUCBOX_NOMAD_JOBS_DIR}}/{{ .CLI_ARGS }}/job.hcl"

  nucbox:nomad:stop:
    desc: Stop nomad job
    deps: [sops:encrypt]
    cmds:
      - ssh {{.NUCBOX_USER}}@{{.NUCBOX_HOST}} "nomad job stop {{ .CLI_ARGS }}"

  postgres:create-migration:
    desc: Create new migration file for postgres
    cmds:
      - migrate create -ext sql -dir ./nomad/jobs/postgres/migrations -seq {{ .CLI_ARGS }}

  nucbox:postgres:apply-migrations:
    desc: Apply postgres migrations
    deps: [sops:decrypt]
    cmds:
      - |
        export PG_PASS=$(uv run scripts/get-content.py nomad/jobs/postgres/secrets/admin_password.raw.yaml)
        export PG_DSN="pgx://postgres:$PG_PASS@127.0.0.1:15432/postgres?sslmode=disable"

        ssh -L 15432:localhost:15432 -N -f {{.NUCBOX_USER}}@{{.NUCBOX_HOST}}

        migrate -database $PG_DSN -path nomad/jobs/postgres/migrations {{ .CLI_ARGS | default "up" }}
