version: "3"

vars:
  HOST: nucbox
  FLAKE: .#{{.HOST}}

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  nixos:switch:
    desc: Apply NixOS configuration (nixos-rebuild switch)
    cmds:
      - sudo nixos-rebuild switch --flake {{.FLAKE}}

  nixos:rebuild:
    desc: Full NixOS rebuild (build + switch)
    cmds:
      - sudo nixos-rebuild boot --flake {{.FLAKE}}
      - sudo reboot
