server:
  externalDomain: "https://immich.cdayz.ru"
  publicUsers: false

oauth:
  enabled: true
  issuerUrl: "https://auth.cdayz.ru/.well-known/openid-configuration"
  clientId: "immich"
  clientSecret: "__IMMICH_OIDC_CLIENT_SECRET__"
  scope: "openid email profile"
  buttonText: "Login with Authelia"
  autoRegister: true
  autoLaunch: false
  mobileOverrideEnabled: false
  signingAlgorithm: "RS256"
  profileSigningAlgorithm: "none"
  tokenEndpointAuthMethod: "client_secret_post"
  timeout: 30000

passwordLogin:
  enabled: false

machineLearning:
  enabled: true
  urls:
    - "http://127.0.0.1:13003"

logging:
  enabled: true
  level: "log"

newVersionCheck:
  enabled: false
