apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://127.0.0.1:19090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki
    orgId: 1
    type: loki
    access: proxy
    url: http://127.0.0.1:13100
    editable: false
