network_bridge_name: br0

network_bridge_members: []
# пример:
# network_bridge_members:
#   - eno1
#   - eno2

network_bridge_use_dhcp: true

network_bridge_static_address: ""
network_bridge_static_gateway: ""
network_bridge_static_dns: []

network_bridge_ipv6_accept_ra: true
network_bridge_enable_resolved: true
network_bridge_link_local_addressing: true

network_bridge_networkd_dir: /etc/systemd/network

network_nameservers:
  - 1.1.1.1
  - 8.8.8.8
