driver: zfs-local-dataset

instance_id: homelab-zfs-local

zfs:
  datasetParentName: tank/nomad-csi
  detachedSnapshotsDatasetParentName: tank/nomad-csi-snapshots
  datasetEnableQuotas: true
  datasetEnableReservation: false

  datasetPermissionsMode: "0770"
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0
